#define SYNC_BYTE_1   0xAA
#define SYNC_BYTE_2   0xAA

#define DATA_QUALITY_LED    13

#define CODE_SIGNAL_QUALITY 0x02
#define CODE_ATTENTION      0x04
#define CODE_MEDITATION     0x05
#define CODE_RAW_WAVE_VALUE 0x80
#define CODE_ASIC_EEG_POWER 0x83